#############
# Functions #
#############

ifeq ($(shell uname -s),Darwin)
define gitsplit
	docker run \
		--rm \
		-e GITSPLIT_GITHUB_API_TOKEN \
		--tty --interactive \
		--volume $(MANALA_CURRENT_DIR):/srv \
		--volume $(HOME)/.ssh:/root/.ssh \
		jderusse/gitsplit
endef
else
define gitsplit
	docker run \
		--rm \
		-e GITSPLIT_GITHUB_API_TOKEN \
		--tty --interactive \
		--volume $(MANALA_CURRENT_DIR):/srv \
		--volume ~/.ssh:/root/.ssh \
		jderusse/gitsplit
endef
endif
